CMPUT301W23T45/CodeCatchers

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/lab_4_codecatchers/LeaderBoardActivity.java
- app/src/main/java/com/example/lab_4_codecatchers/MapActivity.java
- app/src/main/java/com/example/lab_4_codecatchers/ProfileActivity.java
- app/src/main/res/layout/activity_leader_board.xml
- app/src/main/res/layout/activity_map.xml
- app/src/main/res/layout/activity_profile.xml
Created 3 activities and updated the XML files accordingly.
> Created All  4 Activities

- app/src/main/java/com/example/lab_4_codecatchers/LeaderBoardActivity.java
- app/src/main/java/com/example/lab_4_codecatchers/MainActivity.java
- app/src/main/java/com/example/lab_4_codecatchers/MapActivity.java
- app/src/main/java/com/example/lab_4_codecatchers/ProfileActivity.java
- app/src/main/res/layout/activity_leader_board.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_map.xml
- app/src/main/res/layout/activity_profile.xml
- app/src/main/res/values/strings.xml
Connected on click listeners for All Activities for all buttons. Updated app name to Codecatchers from lab_4_Codecachers
> Updates for All Activities.

- app/src/main/java/com/example/lab_4_codecatchers/CameraFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/Code.java
- app/src/main/java/com/example/lab_4_codecatchers/LeaderBoardFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/MapFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/ProfileAdapter.java
- app/src/main/java/com/example/lab_4_codecatchers/ProfileFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/UserWallet.java
- app/src/main/res/drawable/baseline_camera_alt_24.xml
- app/src/main/res/drawable/baseline_format_list_numbered_24.xml
- app/src/main/res/drawable/baseline_map_24.xml
- app/src/main/res/drawable/baseline_person_24.xml
- app/src/main/res/drawable/baseline_qr_code_2_24.xml
- app/src/main/res/layout/activity_signin.xml
- app/src/main/res/layout/activity_splashscreen.xml
- app/src/main/res/layout/fragment_camera.xml
- app/src/main/res/layout/fragment_leader_board.xml
- app/src/main/res/layout/fragment_map.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/layout/profile_list_items.xml
- app/src/main/res/menu/bottom_nav_bar.xml
- app/src/main/res/values/custom_styles.xml
This one adds all the fragment .java and xml files
> I forgot to add the unversioned files in my last commit. 

- .idea/deploymentTargetDropDown.xml
- app/src/main/java/com/example/lab_4_codecatchers/FirstSignInActivity.java
- app/src/main/java/com/example/lab_4_codecatchers/UserWallet.java
Added some updates to the UserWallet to fix crash
> Fixed the sign-in screen crashing

- .idea/deploymentTargetDropDown.xml
- app/src/main/java/com/example/lab_4_codecatchers/FirstSignInActivity.java
- app/src/main/java/com/example/lab_4_codecatchers/UserWallet.java
Reverts CMPUT301W23T45/CodeCatchers#33
When the app is loaded the navigation shows that it is in the leader board but it is in profile view.  the colour purple location is in question
MainActivity has error on line 21, 22,28,29
firstsigninactivity has error on line 49,64,65,66
firestore activity has error on line 12,13,31,42,43,46,47
> Revert "Fixed the sign-in screen crashing" 

- .idea/deploymentTargetDropDown.xml
- app/src/main/java/com/example/lab_4_codecatchers/MainActivity.java
Bug fixed during live discussion. Trying to fix app crash on login.
> Live Discusion

- app/src/main/java/com/example/lab_4_codecatchers/UserWallet.java
> updated the login error. added empty CONSTRUCTORS into UserWallet.java

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/lab_4_codecatchers/CameraFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/MainActivity.java
both camera and location permissions are implemented now. no more bug for only 1 being asked.
> asks for location permissions now

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/lab_4_codecatchers/MainActivity.java
- app/src/main/java/com/example/lab_4_codecatchers/MapFragment.java
- app/src/main/res/layout/fragment_map.xml
Reverts CMPUT301W23T45/CodeCatchers#50
remove all the permission code. already implemented it in the previous pull
> Revert "Map Added". merge conflict errors in main

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/lab_4_codecatchers/MainActivity.java
- app/src/main/java/com/example/lab_4_codecatchers/MapFragment.java
- app/src/main/res/layout/fragment_map.xml
Reverts CMPUT301W23T45/CodeCatchers#52.  I'm getting errors, on my end. someone else should validate it as I am unsure what is happening with the maps. I'll send the pictures with the error on discord.
> Revert "Map with Bugs Fixed Hopefully"

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/lab_4_codecatchers/AddCodeFragment.java
- app/src/main/res/layout/fragment_add_code.xml
When adding a new code now you can also take a picture of the location when you click the plus button. this is done via the credits in the comments. the xml is in line with the demo device. the image is stored via bitmaps.
> Taking a picture of the location is implemented with this pull.

- .idea/deploymentTargetDropDown.xml
- app/src/main/java/com/example/lab_4_codecatchers/AddCodeFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/FireStoreActivity.java
- app/src/main/java/com/example/lab_4_codecatchers/SplashScreenActivity.java
UserWallet now gets saved to Firestore
> Fixed Switch in AddCodeFragment

- .idea/render.experimental.xml
- app/src/main/java/com/example/lab_4_codecatchers/Code.java
- app/src/main/res/layout/activity_signin.xml
- app/src/main/res/layout/activity_splashscreen.xml
- app/src/main/res/layout/fragment_add_code.xml
- app/src/main/res/layout/fragment_camera.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/values/colors.xml
Re-did all xmls so that it works with the demo device. Also changed the colour combo to what we voted on discord. Added the colours and their names to the colors.xml Also added the spaces are the names that are being generated for each QR code.
> Modified UI

- app/src/main/java/com/example/lab_4_codecatchers/AddCodeFragment.java
added code in AddCodeFragment.java so that the photo bitmap is converted into a string so that it can be uploaded. also added code underneath that string that can be converted back to bitmap
> bitmap to string and string to bitmap code added

- app/src/main/java/com/example/lab_4_codecatchers/AddCodeFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/CameraFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/Code.java
- app/src/main/java/com/example/lab_4_codecatchers/MainActivity.java
- app/src/test/java/com/example/lab_4_codecatchers/UserWalletTest.java
updated the code.java so that we can store the string of the bitmap. edited all the tests. also set the image string in the AddCodeFragment.java.
> edited code class to store the image string

- app/src/main/java/com/example/lab_4_codecatchers/FireStoreActivity.java
- app/src/main/java/com/example/lab_4_codecatchers/MapFragment.java
Implemented map markers, set default location on the map to CSC building.  Features to add in the future include tracking users with location permissions enabled, saving geolocation with newly added QR codes, filtering results on the map to focus on the area around the user and hide potential duplicate or already scanned codes.
> Added Map Markers

- app/src/main/java/com/example/lab_4_codecatchers/AddCodeFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/CameraFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/Code.java
- app/src/test/java/com/example/lab_4_codecatchers/UserWalletTest.java
Modified code class. added getters and setters for comments on the code. modified AddCodeFragment.java to store the comments from the user. still need to upload all updates to firestore.
> stores comments now. still need to upload to firebase tho.

- app/src/main/java/com/example/lab_4_codecatchers/CodeViewFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/OtherUsersFragment.java
- app/src/main/res/layout/fragment_code_view.xml
- app/src/main/res/layout/fragment_other_users.xml
Made fragments for Viewing other users. Also made user for viewing users QR codes.
> Made new fragments

- app/build.gradle
- app/src/main/java/com/example/lab_4_codecatchers/AddCodeFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/CameraFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/Code.java
- app/src/main/java/com/example/lab_4_codecatchers/MainActivity.java
- app/src/main/res/layout/fragment_add_code.xml
- app/src/main/res/layout/fragment_camera.xml
AddCodeFragment.java : code added for getting the image and setting it from the internet. link is from api. it will always be unique because hash + user name is always unique. <- assumption
CameraFragment.java : got rid of the extra lines that we used to check what was scanned. now it only says "scan something" once it is scanned it notifies the user that it has be scanned by updating to "code collected"
Code.java : added method to return the image url based on the hash. the refernce url stays the same but the hash makes it uqniue with the addition of the user from the AddCodeFragment.java.
fragment_add_code.xml : resized the image and got rid of the base image. added margins to all sides.
fragment_camera.xml : got rid of the textviews that we used to check what qr code was scanned. only …
> US 02.06.01#19 and removed the testing textview in fragment_camera.xml

- app/build.gradle
- app/src/main/java/com/example/lab_4_codecatchers/AddCodeFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/CameraFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/Code.java
- app/src/main/java/com/example/lab_4_codecatchers/MainActivity.java
- app/src/main/res/layout/fragment_add_code.xml
- app/src/main/res/layout/fragment_camera.xml
Reverts CMPUT301W23T45/CodeCatchers#75
- Got a lot of errors with the Picasso Library
- CameraFragment was also giving me errors.
> Revert "US 02.06.01#19 and removed the testing textview in fragment_camera.xml"

- app/build.gradle
- app/src/main/java/com/example/lab_4_codecatchers/AddCodeFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/CameraFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/Code.java
- app/src/main/java/com/example/lab_4_codecatchers/MainActivity.java
- app/src/main/res/layout/fragment_add_code.xml
- app/src/main/res/layout/fragment_camera.xml
Reverts CMPUT301W23T45/CodeCatchers#76
Reversion turned out to be unnecessary, issues were able to be resolved
> Revert "Revert "US 02.06.01#19 and removed the testing textview in fragment_camera.xml""

- app/src/main/java/com/example/lab_4_codecatchers/CameraFragment.java
Fixed error caused by name collision
> Fixed issue with improperly named camera fragment class

- app/src/main/java/com/example/lab_4_codecatchers/CameraFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/ProfileAdapter.java
- app/src/main/java/com/example/lab_4_codecatchers/ViewPhotoFragment.java
- app/src/main/res/layout/fragment_leader_board.xml
- app/src/main/res/layout/fragment_view_photo.xml
- app/src/main/res/layout/profile_list_items.xml
CameraFragment.java : added where the if statement should go so that the same code is not scanned twice. still not implemented.
fragment_leader_board.xml : Bottom of leaderboard doesn't get cut off now.
fragment_view_photo.xml : Fixed image ration and centered the image.
profile_list_items.xml : added a slight margin for social distancing.
ProfileAdapter.java : Correct corresponding faces are now displayed.
ViewPhotoFragment.java : Fixed spelling mistake.
> minor bug fixes.

- app/src/main/java/com/example/lab_4_codecatchers/AddCodeFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/CameraFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/Code.java
- app/src/main/java/com/example/lab_4_codecatchers/CodeViewFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/FireStoreActivity.java
- app/src/main/java/com/example/lab_4_codecatchers/QRList.java
- app/src/main/java/com/example/lab_4_codecatchers/SplashScreenActivity.java
- app/src/main/java/com/example/lab_4_codecatchers/UserWallet.java
Still need to implement the Firestore part
> Made a QRList Class

- app/build.gradle
- app/src/main/java/com/example/lab_4_codecatchers/MapFragment.java
- app/src/main/res/layout/fragment_map.xml
This completes ticker 5.2.1, now we're just waiting for the QR code portion but the search works.
> Added a search bar to the map and added function to allow user to enter latitude and Longitude.

- app/src/main/java/com/example/lab_4_codecatchers/AddCodeFragment.java
Location is able to be saved now. When fragment is loaded the coordinates are already stored but if the location option is not selected the coordinates are set to 0'0'. It might be better to make it null so that we don't have issues with the map.
default : coordinates saved
if( !geoSave.isChecked() ) { coordinate = 0'0'}
> bug fix for location

- app/src/main/java/com/example/lab_4_codecatchers/MapFragment.java
Used the following resources:
https://www.tabnine.com/code/java/methods/android.widget.SearchView/clearFocus
https://developer.android.com/reference/android/widget/SearchView
> Fixed bug where keyboard did not disappear once user was done searching.

- app/src/main/java/com/example/lab_4_codecatchers/MapFragment.java
Used an OnClickListener, now the user will be able to search by clicking anywhere not the search bar. Specifically using setIconified. 
References: 
https://developer.android.com/reference/android/widget/SearchView
https://www.tabnine.com/code/java/methods/android.widget.SearchView/setIconified
> Now the user can click anywhere on the search bar to start their search.

- .idea/deploymentTargetDropDown.xml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/res/drawable/background.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_signin.xml
- app/src/main/res/layout/activity_splashscreen.xml
- app/src/main/res/layout/code_list_items.xml
- app/src/main/res/layout/fragment_add_code.xml
- app/src/main/res/layout/fragment_camera.xml
- app/src/main/res/layout/fragment_code_view.xml
- app/src/main/res/layout/fragment_leader_board.xml
- app/src/main/res/layout/fragment_other_users.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/layout/leader_board_recycle_view.xml
- app/src/main/res/layout/profile_list_items.xml
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
- build.gradle
> Revert "Changed App Theme"

- app/src/main/java/com/example/lab_4_codecatchers/Code.java
- app/src/main/java/com/example/lab_4_codecatchers/FireStoreActivity.java
- app/src/main/java/com/example/lab_4_codecatchers/LeaderBoardFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/ProfileFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/User.java
- app/src/main/java/com/example/lab_4_codecatchers/UserWallet.java
- app/src/test/java/com/example/lab_4_codecatchers/CodeTest.java
- app/src/test/java/com/example/lab_4_codecatchers/UserTest.java
- app/src/test/java/com/example/lab_4_codecatchers/UserWalletTest.java
> Revert "Updated the Tests"

- app/src/main/java/com/example/lab_4_codecatchers/Code.java
- app/src/main/java/com/example/lab_4_codecatchers/FireStoreActivity.java
- app/src/main/java/com/example/lab_4_codecatchers/LeaderBoardFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/ProfileFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/User.java
- app/src/main/java/com/example/lab_4_codecatchers/UserWallet.java
- app/src/test/java/com/example/lab_4_codecatchers/CodeTest.java
- app/src/test/java/com/example/lab_4_codecatchers/UserTest.java
- app/src/test/java/com/example/lab_4_codecatchers/UserWalletTest.java
testing if its working after restarting the phone
> Revert "Revert "Updated the Tests""

- .idea/deploymentTargetDropDown.xml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/res/drawable/background.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_signin.xml
- app/src/main/res/layout/activity_splashscreen.xml
- app/src/main/res/layout/code_list_items.xml
- app/src/main/res/layout/fragment_add_code.xml
- app/src/main/res/layout/fragment_camera.xml
- app/src/main/res/layout/fragment_code_view.xml
- app/src/main/res/layout/fragment_leader_board.xml
- app/src/main/res/layout/fragment_other_users.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/layout/leader_board_recycle_view.xml
- app/src/main/res/layout/profile_list_items.xml
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
- build.gradle
> Revert "Revert "Changed App Theme""

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/lab_4_codecatchers/CodeViewFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/ProfileFragment.java
- app/src/main/res/layout/fragment_code_view.xml
- app/src/main/res/layout/fragment_leader_board.xml
- app/src/main/res/layout/fragment_map.xml
- app/src/main/res/layout/fragment_profile.xml
- app/src/main/res/values/strings.xml
Redid all xmls to best fit the demo device
fragment_profile.xml : Got rid of the score value for highest and lowest score. also added the section to add the phone.
> edits on xml for demo device

- app/src/main/res/layout/fragment_camera.xml
> redid camera size

- app/src/main/java/com/example/lab_4_codecatchers/CameraFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/CodeViewFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/MapFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/ProfileFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/UserWallet.java
Added alternate colours for caught codes and added ability to click into codes from map
> Navras mapclick

- app/src/main/java/com/example/lab_4_codecatchers/AddCodeFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/CodeViewFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/LeaderBoardFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/MapFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/OtherPlayer.java
- app/src/main/java/com/example/lab_4_codecatchers/ProfileFragment.java
- app/src/main/java/com/example/lab_4_codecatchers/SameQRCodeAdapter.java
- app/src/main/java/com/example/lab_4_codecatchers/UnscannedCodeView.java
- app/src/main/java/com/example/lab_4_codecatchers/ViewPhotoFragment.java
- app/src/main/res/layout/code_list_items.xml
QRList now updates every time a fragment changes
Players who scanned same QR doesn't show score
Location image button in UnscannedCodeView now actually shows a location
> Small functionality updates 

- app/src/main/res/values/strings.xml
Fixed spelling mistake in profile
> Navras gotomap
